export const InterviewState = Object.freeze({
  CREATED: "CREATED",
  READY: "READY",
  IN_PROGRESS: "IN_PROGRESS",
  PROCESSING_ANSWER: "PROCESSING_ANSWER",
  WAITING_FOR_NEXT_QUESTION: "WAITING_FOR_NEXT_QUESTION",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
  EVALUATING: "EVALUATING",
  EVALUATED: "EVALUATED",
});

export default InterviewState;
